//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoDevelop.MSBuildEditor {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ElementDescriptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElementDescriptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MonoDevelop.MSBuildEditor.ElementDescriptions", typeof(ElementDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        internal static string Project_DefaultTargets {
            get {
                return ResourceManager.GetString("Project.DefaultTargets", resourceCulture);
            }
        }
        
        internal static string Project_InitialTargets {
            get {
                return ResourceManager.GetString("Project.InitialTargets", resourceCulture);
            }
        }
        
        internal static string Project_Sdk {
            get {
                return ResourceManager.GetString("Project.Sdk", resourceCulture);
            }
        }
        
        internal static string Project_ToolsVersion {
            get {
                return ResourceManager.GetString("Project.ToolsVersion", resourceCulture);
            }
        }
        
        internal static string Project_TreatAsLocalProperty {
            get {
                return ResourceManager.GetString("Project.TreatAsLocalProperty", resourceCulture);
            }
        }
        
        internal static string Project_xmlns {
            get {
                return ResourceManager.GetString("Project.xmlns", resourceCulture);
            }
        }
        
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        internal static string Target_Name {
            get {
                return ResourceManager.GetString("Target.Name", resourceCulture);
            }
        }
        
        internal static string Target_DependsOnTargets {
            get {
                return ResourceManager.GetString("Target.DependsOnTargets", resourceCulture);
            }
        }
        
        internal static string Target_Inputs {
            get {
                return ResourceManager.GetString("Target.Inputs", resourceCulture);
            }
        }
        
        internal static string Target_Outputs {
            get {
                return ResourceManager.GetString("Target.Outputs", resourceCulture);
            }
        }
        
        internal static string Target_Condition {
            get {
                return ResourceManager.GetString("Target.Condition", resourceCulture);
            }
        }
        
        internal static string Target_KeepDuplicateOutputs {
            get {
                return ResourceManager.GetString("Target.KeepDuplicateOutputs", resourceCulture);
            }
        }
        
        internal static string Target_Returns {
            get {
                return ResourceManager.GetString("Target.Returns", resourceCulture);
            }
        }
        
        internal static string Target_BeforeTargets {
            get {
                return ResourceManager.GetString("Target.BeforeTargets", resourceCulture);
            }
        }
        
        internal static string Target_AfterTargets {
            get {
                return ResourceManager.GetString("Target.AfterTargets", resourceCulture);
            }
        }
        
        internal static string Target_Label {
            get {
                return ResourceManager.GetString("Target.Label", resourceCulture);
            }
        }
        
        internal static string ProjectExtensions {
            get {
                return ResourceManager.GetString("ProjectExtensions", resourceCulture);
            }
        }
        
        internal static string Item_Include {
            get {
                return ResourceManager.GetString("Item.Include", resourceCulture);
            }
        }
        
        internal static string Item_Condition {
            get {
                return ResourceManager.GetString("Item.Condition", resourceCulture);
            }
        }
        
        internal static string Item_Exclude {
            get {
                return ResourceManager.GetString("Item.Exclude", resourceCulture);
            }
        }
        
        internal static string Item_Remove {
            get {
                return ResourceManager.GetString("Item.Remove", resourceCulture);
            }
        }
        
        internal static string Item_Update {
            get {
                return ResourceManager.GetString("Item.Update", resourceCulture);
            }
        }
        
        internal static string Item_Label {
            get {
                return ResourceManager.GetString("Item.Label", resourceCulture);
            }
        }
        
        internal static string Property_Label {
            get {
                return ResourceManager.GetString("Property.Label", resourceCulture);
            }
        }
        
        internal static string Property_Condition {
            get {
                return ResourceManager.GetString("Property.Condition", resourceCulture);
            }
        }
        
        internal static string PropertyGroup {
            get {
                return ResourceManager.GetString("PropertyGroup", resourceCulture);
            }
        }
        
        internal static string PropertyGroup_Condition {
            get {
                return ResourceManager.GetString("PropertyGroup.Condition", resourceCulture);
            }
        }
        
        internal static string PropertyGroup_Label {
            get {
                return ResourceManager.GetString("PropertyGroup.Label", resourceCulture);
            }
        }
        
        internal static string ImportGroup {
            get {
                return ResourceManager.GetString("ImportGroup", resourceCulture);
            }
        }
        
        internal static string ImportGroup_Condition {
            get {
                return ResourceManager.GetString("ImportGroup.Condition", resourceCulture);
            }
        }
        
        internal static string ImportGroup_Label {
            get {
                return ResourceManager.GetString("ImportGroup.Label", resourceCulture);
            }
        }
        
        internal static string ItemGroup {
            get {
                return ResourceManager.GetString("ItemGroup", resourceCulture);
            }
        }
        
        internal static string ItemGroup_Condition {
            get {
                return ResourceManager.GetString("ItemGroup.Condition", resourceCulture);
            }
        }
        
        internal static string ItemGroup_Label {
            get {
                return ResourceManager.GetString("ItemGroup.Label", resourceCulture);
            }
        }
        
        internal static string ItemDefinitionGroup {
            get {
                return ResourceManager.GetString("ItemDefinitionGroup", resourceCulture);
            }
        }
        
        internal static string ItemDefinitionGroup_Condition {
            get {
                return ResourceManager.GetString("ItemDefinitionGroup.Condition", resourceCulture);
            }
        }
        
        internal static string ItemDefinitionGroup_Label {
            get {
                return ResourceManager.GetString("ItemDefinitionGroup.Label", resourceCulture);
            }
        }
        
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        internal static string Choose_Label {
            get {
                return ResourceManager.GetString("Choose.Label", resourceCulture);
            }
        }
        
        internal static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        internal static string When_Condition {
            get {
                return ResourceManager.GetString("When.Condition", resourceCulture);
            }
        }
        
        internal static string Otherwise {
            get {
                return ResourceManager.GetString("Otherwise", resourceCulture);
            }
        }
        
        internal static string OnError {
            get {
                return ResourceManager.GetString("OnError", resourceCulture);
            }
        }
        
        internal static string OnError_Condition {
            get {
                return ResourceManager.GetString("OnError.Condition", resourceCulture);
            }
        }
        
        internal static string OnError_ExecuteTargets {
            get {
                return ResourceManager.GetString("OnError.ExecuteTargets", resourceCulture);
            }
        }
        
        internal static string OnError_Label {
            get {
                return ResourceManager.GetString("OnError.Label", resourceCulture);
            }
        }
        
        internal static string UsingTask {
            get {
                return ResourceManager.GetString("UsingTask", resourceCulture);
            }
        }
        
        internal static string UsingTask_Condition {
            get {
                return ResourceManager.GetString("UsingTask.Condition", resourceCulture);
            }
        }
        
        internal static string UsingTask_AssemblyName {
            get {
                return ResourceManager.GetString("UsingTask.AssemblyName", resourceCulture);
            }
        }
        
        internal static string UsingTask_AssemblyFile {
            get {
                return ResourceManager.GetString("UsingTask.AssemblyFile", resourceCulture);
            }
        }
        
        internal static string UsingTask_TaskName {
            get {
                return ResourceManager.GetString("UsingTask.TaskName", resourceCulture);
            }
        }
        
        internal static string UsingTask_TaskFactory {
            get {
                return ResourceManager.GetString("UsingTask.TaskFactory", resourceCulture);
            }
        }
        
        internal static string UsingTask_Architecture {
            get {
                return ResourceManager.GetString("UsingTask.Architecture", resourceCulture);
            }
        }
        
        internal static string UsingTask_Runtime {
            get {
                return ResourceManager.GetString("UsingTask.Runtime", resourceCulture);
            }
        }
        
        internal static string ParameterGroup {
            get {
                return ResourceManager.GetString("ParameterGroup", resourceCulture);
            }
        }
        
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        internal static string Parameter_ParameterType {
            get {
                return ResourceManager.GetString("Parameter.ParameterType", resourceCulture);
            }
        }
        
        internal static string Parameter_Output {
            get {
                return ResourceManager.GetString("Parameter.Output", resourceCulture);
            }
        }
        
        internal static string Parameter_Required {
            get {
                return ResourceManager.GetString("Parameter.Required", resourceCulture);
            }
        }
        
        internal static string UsingTaskBody {
            get {
                return ResourceManager.GetString("UsingTaskBody", resourceCulture);
            }
        }
        
        internal static string UsingTaskBody_Evaluate {
            get {
                return ResourceManager.GetString("UsingTaskBody.Evaluate", resourceCulture);
            }
        }
        
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        internal static string Import_Condition {
            get {
                return ResourceManager.GetString("Import.Condition", resourceCulture);
            }
        }
        
        internal static string Import_Project {
            get {
                return ResourceManager.GetString("Import.Project", resourceCulture);
            }
        }
        
        internal static string Import_Label {
            get {
                return ResourceManager.GetString("Import.Label", resourceCulture);
            }
        }
        
        internal static string Import_Sdk {
            get {
                return ResourceManager.GetString("Import.Sdk", resourceCulture);
            }
        }
        
        internal static string Import_Version {
            get {
                return ResourceManager.GetString("Import.Version", resourceCulture);
            }
        }
        
        internal static string Import_MinimumVersion {
            get {
                return ResourceManager.GetString("Import.MinimumVersion", resourceCulture);
            }
        }
        
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        internal static string Output_TaskParameter {
            get {
                return ResourceManager.GetString("Output.TaskParameter", resourceCulture);
            }
        }
        
        internal static string Output_ItemName {
            get {
                return ResourceManager.GetString("Output.ItemName", resourceCulture);
            }
        }
        
        internal static string Output_PropertyName {
            get {
                return ResourceManager.GetString("Output.PropertyName", resourceCulture);
            }
        }
        
        internal static string Output_Condition {
            get {
                return ResourceManager.GetString("Output.Condition", resourceCulture);
            }
        }
        
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        internal static string Task_Condition {
            get {
                return ResourceManager.GetString("Task.Condition", resourceCulture);
            }
        }
        
        internal static string Task_ContinueOnError {
            get {
                return ResourceManager.GetString("Task.ContinueOnError", resourceCulture);
            }
        }
        
        internal static string Task_Architecture {
            get {
                return ResourceManager.GetString("Task.Architecture", resourceCulture);
            }
        }
        
        internal static string Task_Runtime {
            get {
                return ResourceManager.GetString("Task.Runtime", resourceCulture);
            }
        }
        
        internal static string Task_Parameter {
            get {
                return ResourceManager.GetString("Task.Parameter", resourceCulture);
            }
        }
        
        internal static string Metadata_Condition {
            get {
                return ResourceManager.GetString("Metadata.Condition", resourceCulture);
            }
        }
        
        internal static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        internal static string TaskBody {
            get {
                return ResourceManager.GetString("TaskBody", resourceCulture);
            }
        }
        
        internal static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        internal static string ItemDefinition {
            get {
                return ResourceManager.GetString("ItemDefinition", resourceCulture);
            }
        }
    }
}
