//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoDevelop.MSBuild.Language.Syntax {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpUrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpUrls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonoDevelop.MSBuild.Language.Syntax.HelpUrls", typeof(HelpUrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/msbuild-conditions.
        /// </summary>
        internal static string Attribute_Condition {
            get {
                return ResourceManager.GetString("Attribute_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/how-to-exclude-files-from-the-build.
        /// </summary>
        internal static string Attribute_Item_Exclude {
            get {
                return ResourceManager.GetString("Attribute_Item_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/how-to-select-the-files-to-build.
        /// </summary>
        internal static string Attribute_Item_Include {
            get {
                return ResourceManager.GetString("Attribute_Item_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/choose-element-msbuild.
        /// </summary>
        internal static string Element_Choose {
            get {
                return ResourceManager.GetString("Element_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/import-element-msbuild.
        /// </summary>
        internal static string Element_Import {
            get {
                return ResourceManager.GetString("Element_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/importgroup-element.
        /// </summary>
        internal static string Element_ImportGroup {
            get {
                return ResourceManager.GetString("Element_ImportGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/item-element-msbuild.
        /// </summary>
        internal static string Element_Item {
            get {
                return ResourceManager.GetString("Element_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/itemdefinitiongroup-element-msbuild.
        /// </summary>
        internal static string Element_ItemDefinitionGroup {
            get {
                return ResourceManager.GetString("Element_ItemDefinitionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/itemgroup-element-msbuild.
        /// </summary>
        internal static string Element_ItemGroup {
            get {
                return ResourceManager.GetString("Element_ItemGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/itemmetadata-element-msbuild.
        /// </summary>
        internal static string Element_Metadata {
            get {
                return ResourceManager.GetString("Element_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/onerror-element-msbuild.
        /// </summary>
        internal static string Element_OnError {
            get {
                return ResourceManager.GetString("Element_OnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/otherwise-element-msbuild.
        /// </summary>
        internal static string Element_Otherwise {
            get {
                return ResourceManager.GetString("Element_Otherwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/output-element-msbuild.
        /// </summary>
        internal static string Element_Output {
            get {
                return ResourceManager.GetString("Element_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/parameter-element.
        /// </summary>
        internal static string Element_Parameter {
            get {
                return ResourceManager.GetString("Element_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/parametergroup-element.
        /// </summary>
        internal static string Element_ParameterGroup {
            get {
                return ResourceManager.GetString("Element_ParameterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/project-element-msbuild.
        /// </summary>
        internal static string Element_Project {
            get {
                return ResourceManager.GetString("Element_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/projectextensions-element-msbuild.
        /// </summary>
        internal static string Element_ProjectExtensions {
            get {
                return ResourceManager.GetString("Element_ProjectExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/property-element-msbuild.
        /// </summary>
        internal static string Element_Property {
            get {
                return ResourceManager.GetString("Element_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/propertygroup-element-msbuild.
        /// </summary>
        internal static string Element_PropertyGroup {
            get {
                return ResourceManager.GetString("Element_PropertyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/sdk-element-msbuild.
        /// </summary>
        internal static string Element_Sdk {
            get {
                return ResourceManager.GetString("Element_Sdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/target-element-msbuild.
        /// </summary>
        internal static string Element_Target {
            get {
                return ResourceManager.GetString("Element_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/task-element-msbuild.
        /// </summary>
        internal static string Element_Task {
            get {
                return ResourceManager.GetString("Element_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/taskbody-element-msbuild.
        /// </summary>
        internal static string Element_TaskBody {
            get {
                return ResourceManager.GetString("Element_TaskBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/usingtask-element-msbuild.
        /// </summary>
        internal static string Element_UsingTask {
            get {
                return ResourceManager.GetString("Element_UsingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/visualstudio/msbuild/when-element-msbuild.
        /// </summary>
        internal static string Element_When {
            get {
                return ResourceManager.GetString("Element_When", resourceCulture);
            }
        }
    }
}
